# Generated by Django 4.1.4 on 2023-01-13 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0002_alter_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_order_prodinfo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
