# Generated by Django 4.1.4 on 2023-01-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0003_invoice_invoice_order_prodinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_delivery_due_date_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('P', 'Pending'), ('D', 'Done')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_finance_date_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('P', 'Pending'), ('D', 'Done')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_mra_date_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('P', 'Pending'), ('D', 'Done')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_pac_date_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('P', 'Pending'), ('D', 'Done')], default='', max_length=2, null=True),
        ),
    ]
